# Generated by Django 3.2.4 on 2022-04-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_prescription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
    ]
