# Generated by Django 3.2.4 on 2022-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_prescription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='user_prescription',
            field=models.ImageField(upload_to='Prescription/'),
        ),
    ]
