# Generated by Django 3.2.4 on 2022-04-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0008_rename_date2_returnmedicine_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentamount', models.IntegerField()),
                ('paymentdate', models.DateField()),
                ('paymenttype', models.CharField(default='cash', max_length=10, verbose_name=['esewa', 'esewa', 'khalti', 'khalti', 'cash', 'cash'])),
                ('paymentreceiver', models.CharField(max_length=10)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
