# Generated by Django 3.2.4 on 2022-04-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='is_active',
        ),
    ]
