# Generated by Django 3.2.4 on 2022-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_remove_medicine_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, upload_to='Medicine/'),
        ),
    ]
