# Generated by Django 3.2.4 on 2022-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_alter_medicine_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(default='default.jpg', upload_to='medicine/'),
        ),
    ]
