# Generated by Django 3.2.4 on 2022-04-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_medicine_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=55)),
                ('companycountry', models.CharField(max_length=55)),
                ('companyestd', models.CharField(max_length=55)),
                ('companycontact', models.CharField(max_length=55)),
                ('companycertified', models.BooleanField()),
            ],
        ),
    ]
