# Generated by Django 3.2.4 on 2022-04-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status2',
        ),
    ]
