# Generated by Django 3.2.4 on 2022-04-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_status2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('medicine', models.CharField(max_length=500)),
                ('Reason', models.TextField(help_text='Please confirm the return by stating the appropriate reason for the return')),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('date_ordersuccess', models.DateField()),
            ],
        ),
    ]
