# Generated by Django 3.2.4 on 2022-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_returnmedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnmedicine',
            name='medicine',
            field=models.CharField(max_length=50),
        ),
    ]
