# Generated by Django 3.2.4 on 2022-04-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_date_returnmedicine_date2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnmedicine',
            old_name='date2',
            new_name='date',
        ),
    ]
